name: boteco_pro
description: "Gestão completa para seu bar"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_animate: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  table_calendar: ^3.0.0
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.0.0
  intl: ^0.20.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: ^1.1.1
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  http: ^1.0.0
  uuid: ^4.5.1
  sqlite3: ^2.1.0
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.10.3
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Assets (opcional - .env é carregado dinamicamente)
  assets:
    - .env
