CREATE TABLE catalog.Category (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE catalog.Supplier (
    supplier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    notes TEXT
);

CREATE TABLE catalog.Ingredient (
    ingredient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    unit_of_measure VARCHAR(20) NOT NULL,
    cost_price NUMERIC(10,2),
    stock_quantity NUMERIC(10,2),
    stock_minimum NUMERIC(10,2),
    reorder_quantity NUMERIC(10,2),
    last_order_date DATE,
    supplier_id INTEGER,
    FOREIGN KEY (supplier_id) REFERENCES catalog.Supplier(supplier_id)
);

CREATE TABLE catalog.Recipe (
    recipe_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    base_price NUMERIC(10,2),
    preparation_time TIME,
    category_id INTEGER,
    notes TEXT,
    FOREIGN KEY (category_id) REFERENCES catalog.Category(category_id)
);

CREATE TABLE catalog.Recipe_Ingredient (
    recipe_id INTEGER,
    ingredient_id INTEGER,
    quantity NUMERIC(10,2),
    PRIMARY KEY (recipe_id, ingredient_id),
    FOREIGN KEY (recipe_id) REFERENCES catalog.Recipe(recipe_id),
    FOREIGN KEY (ingredient_id) REFERENCES catalog.Ingredient(ingredient_id)
);

CREATE TABLE catalog.Recipe_Addition (
    addition_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INTEGER,
    name VARCHAR(100),
    extra_cost NUMERIC(10,2),
    FOREIGN KEY (recipe_id) REFERENCES catalog.Recipe(recipe_id)
);

CREATE TABLE catalog.Addition_Ingredient (
    addition_id INTEGER,
    ingredient_id INTEGER,
    quantity NUMERIC(10,2),
    PRIMARY KEY (addition_id, ingredient_id),
    FOREIGN KEY (addition_id) REFERENCES catalog.Recipe_Addition(addition_id),
    FOREIGN KEY (ingredient_id) REFERENCES catalog.Ingredient(ingredient_id)
);