#!/usr/bin/env bash
: "${SUPABASE_URL:?SUPABASE_URL não definido}"
: "${SUPABASE_ANON_KEY:?SUPABASE_ANON_KEY não definido}"
: "${GITHUB_TOKEN:?GITHUB_TOKEN não definido}"
: "${POSTGRES_USER:?POSTGRES_USER não definido}"
: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD não definido}"
: "${POSTGRES_DB:?POSTGRES_DB não definido}"
: "${POSTGRES_HOST:?POSTGRES_HOST não definido}"
: "${POSTGRES_PORT:?POSTGRES_PORT não definido}"
echo "🔍 Variáveis ok"
