#!/usr/bin/env bash
: "${SUPABASE_URL:?SUPABASE_URL não definido}"
: "${SUPABASE_ANON_KEY:?SUPABASE_ANON_KEY não definido}"
: "${SUPABASE_PROJECT_ID:?SUPABASE_PROJECT_ID não definido}"
: "${GITHUB_TOKEN:?GITHUB_TOKEN não definido}"
SUPABASE_CLI_VERSION="${SUPABASE_CLI_VERSION:-2.31.8}"
echo "🔍 Variáveis ok  | CLI v$SUPABASE_CLI_VERSION"
